spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newbatch?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: beh73167380!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  batch:
    job:
      names: ${job.name:NONE}
